language: cpp
compiler:
- clang
addons:
  apt:
    packages:
    - g++-multilib
    - lib32z1-dev
install:
- git clone https://github.com/alliedmodders/ambuild.git $TRAVIS_BUILD_DIR/../ambuild
  && cd $TRAVIS_BUILD_DIR/../ambuild && python setup.py build && sudo python setup.py
  install
- git clone https://github.com/alliedmodders/metamod-source.git -b 1.10-dev $TRAVIS_BUILD_DIR/../metamod-source
- git clone https://github.com/alliedmodders/sourcemod.git --recursive -b 1.8-dev
  $TRAVIS_BUILD_DIR/../sourcemod
- cd $TRAVIS_BUILD_DIR/../
- wget https://raw.githubusercontent.com/alliedmodders/sourcemod/master/tools/checkout-deps.sh && chmod +x checkout-deps.sh
- ./checkout-deps.sh
script:
- mkdir $TRAVIS_BUILD_DIR/build && cd $TRAVIS_BUILD_DIR/build
- python ../configure.py --enable-optimize
- ambuild
before_deploy:
- cd $TRAVIS_BUILD_DIR/build/package
- zip -r example.zip *
deploy:
  provider: releases
  api_key:
    secure: oA+PoBS2zqotnQfPvmc68vz3ke6TEprGa6t4uLYwdHnIMGz3NTdUzXppCaotUnItHSaBhfFM4v3JEtQWU/LgOpvk/VpGW2eNwHau+Z+C/ESgNShFvXK8XU9TubaC1lxhB4D/vBSpqun2d5EA2qJcOpFXm1o7HYlGjLcSSl81Nc/IQ8kP5aKIt/1gHitHwZCBBrsm2QkmDAGtJOaEIvo0G2Xv/LzROHKe9B/JmTtQzgG6w/FN+mbHEBntIfvHgqq39Au95YOfTWai5P4vYQoZohclyhS5Ok8cmIMRbJYA9We4drIbtRsuk4ncX+GW6SXdkIdVkfeMIBVum/A0dM/cogYKr6KACMGBpqrZhNdfA7lh76za4OblYeE2nDee1UYnPhUJ9QZjdNY9ZFqRm4+uodBQHIJzqrGBSz0sYjovK8DpOYuiUH+QyTMeRwafaiRVeHxXlcso91dnEsHuljsbztEPYQm97xgC+KBGzuuaw+yveBde0+C3jo4/D+lpMVI/QWMGBzrjlNnN3VuUQNFx17697HNyZT8upvo0dhreABBhrnLDb5hp5z/HuKLDFhjiVtv/BPc7UwGIyZDEB9FbFxgm2b+LvBdtlvcCa41iYNa+D4CmX5+otL9JH+iAbH00FGmRmY0uMWsbBFFSagZ0FkZVI674mzg3AYu3x747cYI=
  file: $TRAVIS_BUILD_DIR/build/package/example.zip
  on:
    repo: servadestroya/sample_ext
